site_name: SQL & Java - Your getting started Guide
site_url: https://rainbowdashlabs.github.io/BasicSQLPlugin/
site_description: Your goto page when you start with java and sql.
repo_url: https://github.com/RainbowDashLabs/BasicSQLPlugin/
repo_name: Basic SQL Plugin
plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
nav:
  - Home: index.md
  - 'Chapter 1 Getting Started':
    - 'Preface': 01/preface.md
    - 'Introduction': 01/introduction.md
    - 'About Databases': 01/about_databases.md
    - 'Project Setup': 01/setup.md
  - 'Chapter 2 Basic Data Operations':
    - 'Operators': 02/operators.md
    - 'SQL Datatypes': 02/sql_datatypes.md
    - 'Datatypes':
      - 'SQLite': 02/datatypes/sqlite.md
      - 'MariaDB and MySQL': 02/datatypes/mariadb_mysql.md
      - 'PostgreSQL': 02/datatypes/postgresql.md
    - 'Naming Conventions': 02/naming.md
    - 'Code Style': 02/code_style.md
    - 'Database Creation': 02/database_creation.md
    - 'Tables': 02/tables.md
    - 'Insert': 02/insert.md
    - 'Select': 02/select.md
theme:
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.expand
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.annotate
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
